name: Build App

on:
    push:
        branches:
        - master

jobs:
    owasp :
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
        - uses: sburris/dependency-check-action@master
          with:
            Project-Name: TestApp
        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: reports
            path: reports        
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: yani1erdunom/cd
            #tag_with_sha: true
            tags: latest
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'docker.io/yani1erdunom/my-app:latest'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: 'trivy-results.sarif'